### ISSUE TITLE
Go code for any topic from the Go-Playbook

### ISSUE THREAD

**Issue by priyamm** [priyamm/go-playbook#2]
The playbook contains Go concepts for every level in separate section, you can add your code as per your choice.

If needed we can add new sections.

**Comment by iamjoross** [comment]
Hi @priyamm , I'm interested in working on this.

**Comment by priyamm** [comment]
@iamjoross yeah sure, the Issue is open for all, you can raise the PR.

**Comment by applegreengrape** [comment]
#6 - add go method
